### PR TITLE
Add CSV example

### LINKED ISSUE #32: import CSV file
i want to import a CSV file in my Magento, it's possible?
thanks

### PR DESCRIPTION
**Pull request by barryvdh**
As you write:
> The glaringly obvious one: being able to do imports programmatically rather than manually uploading a CSV file.

It's might be easy to provide an actual example :)

(Also fixed the Exception, only that type supports the CustomMessage)
Also fixes #32

### CODE REVIEW

**Comment by danslo** [comment]
Thanks! :+1:

**Comment by Nolaan** [comment]
Still no example CSV???

**Comment by barryvdh** [comment]
Just export a CSV from the admin panel with some actual product data.

**Comment by Nolaan** [comment]
I did it. For my use case I need to import products. I omitted several fields in the header, the result I obtain is "import_failed: Invalid entity model". Does it means that all 54 fields must be used?

**Comment by barryvdh** [comment]
Did you set a EntityModel? If so, are you sure it's correct?

**Comment by Nolaan** [comment]
Actually I don't know neither the exported then reimported csv nor the provided csv here https://www.mag-manager.com/useful-articles/tipstricks/required-csv-file-values-for-error-free-magento-import-via-admin/ works. I'll just give up on that I guess.

**Pull request merged**
